general:
  debug: false
  
map:
  directory: maps
  config: map.xml
  
rotation:
  file: rotation.txt
  
match:
  prefix: match-
  
team:
  default-name: Observers
  default-color: AQUA
  default-max: 1000